[project]
name = "gymtime"
version = ""
description = ""
authors = [
    {name = "ninest", email = "parth.kabra@gmail.com"},
]
dependencies = [
    "black>=22.12.0",
    "sqlmodel>=0.0.8",
]
requires-python = ">=3.8"
license = {text = "MIT"}

[tool.pdm]

[build-system]
requires = ["pdm-pep517>=1.0.0"]
build-backend = "pdm.pep517.api"
